### ISSUE TITLE
Internal error in CORSMiddleware on Ubuntu 22.04

### ISSUE THREAD

**Issue by wagner-intevation** [certtools/intelmq-api#41] opened 2023-01-31 11:45 UTC
Running [intelmq-vagrant](https://github.com/certtools/intelmq-vagrant) with Ubuntu 22.04 revealed yet another incompatibility with hug/falcon on newer plattforms:

```
[Tue Jan 31 11:38:52.000973 2023] [wsgi:error] [pid 5375:tid 140181172622912] [client 127.0.0.1:53728] Loading config from /etc/intelmq/api-config.json
[Tue Jan 31 11:38:52.001116 2023] [wsgi:error] [pid 5375:tid 140181172622912] [client 127.0.0.1:53728] mod_wsgi (pid=5375): Exception occurred processing WSGI script '/usr/lib/python3/dist-packages/intelmq_api/intelmq-api.wsgi'.
[Tue Jan 31 11:38:52.001281 2023] [wsgi:error] [pid 5375:tid 140181172622912] [client 127.0.0.1:53728] Traceback (most recent call last):
[Tue Jan 31 11:38:52.001297 2023] [wsgi:error] [pid 5375:tid 140181172622912] [client 127.0.0.1:53728]   File "/usr/lib/python3/dist-packages/intelmq_api/intelmq-api.wsgi", line 11, in application
[Tue Jan 31 11:38:52.001299 2023] [wsgi:error] [pid 5375:tid 140181172622912] [client 127.0.0.1:53728]     from intelmq_api.serve import __hug_wsgi__
[Tue Jan 31 11:38:52.001302 2023] [wsgi:error] [pid 5375:tid 140181172622912] [client 127.0.0.1:53728]   File "/usr/lib/python3/dist-packages/intelmq_api/serve.py", line 31, in <module>
[Tue Jan 31 11:38:52.001303 2023] [wsgi:error] [pid 5375:tid 140181172622912] [client 127.0.0.1:53728]     api.http.add_middleware(hug.middleware.CORSMiddleware(api, allow_origins=api_config.allow_origins))
[Tue Jan 31 11:38:52.001313 2023] [wsgi:error] [pid 5375:tid 140181172622912] [client 127.0.0.1:53728]   File "falcon/middleware.py", line 39, in falcon.middleware.CORSMiddleware.__init__
[Tue Jan 31 11:38:52.001321 2023] [wsgi:error] [pid 5375:tid 140181172622912] [client 127.0.0.1:53728] TypeError: __init__() got multiple values for keyword argument 'allow_origins'
```

**Comment by sebix** [comment] 2023-02-14 18:26
Duplicate of #40

**Closed as completed by sebix** 2023-02-14 18:26 UTC
